apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth-operator
  name: auth-operator
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-operator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: auth-operator
      namespace: kube-system
    spec:
      automountServiceAccountToken: true
      serviceAccount: auth-operator
      containers:
        - args:
            - --verbose
            - --liveness=http://0.0.0.0:8080/healthz
            - --standalone
          image: coveo/aws-auth-operator:0.1
          imagePullPolicy: IfNotPresent
          name: operator
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            periodSeconds: 900
            timeoutSeconds: 30
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: kube-system
  name: auth-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: auth-operator-role-cluster
rules:
  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [zalando.org]
    resources: [kopfpeerings, clusterkopfpeerings]
    verbs: [list, watch, patch, get]

  # Framework: posting the events about the handlers progress/errors.
  - apiGroups: [events.k8s.io]
    resources: [events]
    verbs: [create]
  - apiGroups: [""]
    resources: [events]
    verbs: [create]

  # Application: watching & handling for the custom resource we declare.
  - apiGroups: [iamauthenticator.k8s.aws]
    resources: [iamidentitymappings]
    verbs: [list, watch, patch, get]

  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, get, update, create, patch]

  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: auth-operator-rolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: auth-operator-role-cluster
subjects:
  - kind: ServiceAccount
    name: auth-operator
    namespace: kube-system
---
