---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: iamidentitymappings.iamauthenticator.k8s.aws
spec:
  group: iamauthenticator.k8s.aws
  version: v1
  scope: Cluster
  names:
    plural: iamidentitymappings
    singular: iamidentitymapping
    kind: IAMIdentityMapping
    categories:
      - all
  validation:
    openAPIV3Schema:
      properties:
        spec:
          oneOf:
          - required:
            - userarn
            - username
          - required:
            - rolearn
            - username
          properties:
            groups:
              items:
                type: string
              type: array
            userarn:
              type: string
            rolearn:
              type: string
            username:
              type: string
          type: object
      type: object