---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: iamidentitymappings.iamauthenticator.k8s.aws
spec:
  group: iamauthenticator.k8s.aws
  names:
    categories:
    - all
    kind: IAMIdentityMapping
    plural: iamidentitymappings
    singular: iamidentitymapping
  scope: Cluster
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          properties:
            spec:
              oneOf:
              - required:
                - userarn
                - username
              - required:
                - rolearn
                - username
              properties:
                groups:
                  items:
                    type: string
                  type: array
                rolearn:
                  type: string
                userarn:
                  type: string
                username:
                  type: string
              type: object
          type: object
