name: 'Dependency Review'

on:
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  pull-requests: write

jobs:
    dependency-Review:
      uses: coveo/public-actions/.github/workflows/dependency-review.yml@91d70ccf7c68777b63239f0a19110caf8bb2b23b # main
      with:
        public: true
        distributed: true
        runs-on: '["ubuntu-latest"]'
