name: Build and push image

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Semantic version to be built"
        required: true
        type: string

permissions:
  contents: read

jobs:
  push_to_registries:
    name: Push Docker image to Dockerhub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2
      with:
        egress-policy: audit

    - name: Check out the repo
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        
    - name: Login to GitHub Container Registry
      uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ github.token }}
      
    - name: Build and push Docker images
      uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f
      with:
        context: .
        push: true
        tags: ghcr.io/coveooss/aws_auth_eks_crd:${{ github.event.inputs.version }}
        labels: ${{ github.event.inputs.version }}
