name: Build and push image

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Semantic version to be built"
        required: true
        type: string

permissions:
  contents: read

jobs:
  push_to_registries:
    name: Push Docker image to Dockerhub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2
      with:
        egress-policy: audit

    - name: Check out the repo
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        
    - name: Login to GitHub Container Registry
      uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ github.token }}
      
    - name: Build and push Docker images
      uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f
      with:
        context: .
        push: true
        tags: ghcr.io/coveooss/aws_auth_eks_crd:${{ github.event.inputs.version }}
        labels: ${{ github.event.inputs.version }}
